ohca/urls.py
from django.contrib import admin
from django.urls import path
from ohca import views
from django.views.decorators.cache import cache_page
from ohca.views import eureca

from ohca.views import index

pageCacheTimeout = 24 * 60 * 60

urlpatterns = [
    path('admin/', admin.site.urls),
    path('download/', views.download),
    path('summary/', index.as_view()),
    path('dsz/', views.dsz),
    # path('summary2/', views.http_response),
    path('case/id/', views.case_by_id, name='case'),
    path('case/id/multi/', views.case_by_id_multi, name='case_multi'),
    path('case/dispatch/', views.case_by_disp, name='dispatch'),
    path('case/dispatch/multi/', views.case_by_disp_multi, name='dispatch_multi'),
    path('system/', views.system_view, name='system'),
    path('locale/', views.locale_view, name='locale'),
    # path('autoform/', views.index22),
    # path('', index.as_view())
    path("", cache_page(pageCacheTimeout)(views.new_index), name="index"),
    path("dsz-1-dan", views.form_name_view, name="form_name"),
    path("30-dan", views.second_form_name_view, name="second_form_name"),
    # path("dsz-retro", views.third_form_name_view, name="third_form_name"),
    path("ndsz-1-dan", views.second_first_form_name_view, name="second_first_formpage"),
    path("popravki", views.error_form_view, name="error_page"),
    # path("ndsz-retro", views.second_third_form_name_view, name="second_third_form_name"),
    # path("test-form", views.test_view, name="test_page")
    path('eureca/', eureca.as_view()),
    path('download-eureca/', views.download_eureca),
]

ohca/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Locale(models.Model):
    localID = models.BigAutoField(primary_key=True)
    friendlyName = models.TextField()
    population = models.IntegerField(default = 0)
    attendedCAs = models.IntegerField(default = 0)
    attemptedResusc = models.IntegerField(default = 0)
    casesDNR = models.IntegerField(default = 0)
    casesFutile = models.IntegerField(default = 0)
    casesCirculation = models.IntegerField(default = 0)
    casesUnknown = models.IntegerField(default = 0)
    description = models.JSONField(default = dict)
    descriptionSupplemental = models.TextField(null = True, blank = True)
    
    def update(self, *args, **kwargs):
        for name,values in kwargs.items():
            if not(name == 'localID'):
                try:
                    setattr(self,name,values)
                except KeyError:
                    pass
        self.save()
        return True

    def __str__(self):
        return self.friendlyName

    class Meta:
        ordering = ('friendlyName',) # orders them alphabetically in drop down menu
        db_table = 'locales'

class System(models.Model):
    systemID = models.BigAutoField(primary_key=True)
    friendlyName = models.TextField()
    population = models.IntegerField(default = 0)
    attendedCAs = models.IntegerField(default = 0)
    attemptedResusc = models.IntegerField(default = 0)
    casesDNR = models.IntegerField(default = 0)
    casesFutile = models.IntegerField(default = 0)
    casesCirculation = models.IntegerField(default = 0)
    casesUnknown = models.IntegerField(default = 0)
    description = models.JSONField(default = dict)
    descriptionSupplemental = models.TextField(null = True, blank = True)
    
    def update(self, *args, **kwargs):
        for name,values in kwargs.items():
            if not(name == 'systemID'):
                try:
                    setattr(self,name,values)
                except KeyError:
                    pass
        self.save()
        return True

    def __str__(self):
        return self.friendlyName
    
    class Meta:
        ordering = ('friendlyName',) # orders them alphabetically in drop down menu
        db_table = 'systems'

class CaseReport(models.Model):
    numID = models.BigAutoField(primary_key=True)
    caseID = models.CharField(max_length = 64, blank = True, null = True, db_index = True) 
    dispatchID = models.CharField(max_length = 64, blank = True, null = True, db_index = True)
    systemID = models.ForeignKey(System, on_delete = models.DO_NOTHING, null = True)
    localID = models.ForeignKey(Locale, on_delete = models.DO_NOTHING, null = True)

    reaPop = models.IntegerField(null=True, blank=True)
    interventionID = models.CharField(max_length=12, blank = True, null = True) 
    mainInterventionID = models.CharField(max_length=12, blank = True, null = True) 

    emergencyTransport = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(0), MaxValueValidator(1)])
    cardiacArrest = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(0), MaxValueValidator(1)])

    dispIdentifiedCA = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    dispProvidedCPRinst = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    callTimestamp = models.DateTimeField(null = True, blank = True)
    estimatedCallTimestamp = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(0), MaxValueValidator(1)])
    firstResponder = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    noFirstResponder = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(3)])
 
    dateOfCA = models.DateField(blank=True, null=True)
    name = models.CharField(max_length=200, blank = True, null = True)
    surname = models.CharField(max_length=200, blank = True, null = True)
    age = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(200)])
    estimatedAge = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(200)])
    dateOfBirth = models.DateField(null=True, blank=True)
    gender = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(2)])
    genderUtstein = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    witnesses = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(3)])
    reaWitnesses = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(3)])

    location  = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(8)])
    reaLocation = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(6)])
    CAtimestamp = models.DateTimeField(null=True, blank=True) # time of CA
    estimatedCAtimestamp = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])

    bystanderResponse = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(2)])
    bystanderResponseTime = models.BigIntegerField(null = True, blank = True)
    bystanderResponseTimestamp = models.DateTimeField(null = True, blank = True)

    bystanderCPR = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(3)])
    CPRdone = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])

    bystanderAED = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(2)])
    bystanderAEDTime = models.BigIntegerField(null = True, blank = True),
    bystanderAEDTimestamp = models.DateTimeField(null = True, blank = True)

    deadOnArrival = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    diedOnField = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)]) # ali je bolnik umrl na terenu

    firstMonitoredRhy = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(7)])
    iniRythm = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    pathogenesis = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(6)])
    independentLiving = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    comorbidities = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    vad = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    cardioverterDefib = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(2)])
    stemiPresent = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])

    responseTime = models.BigIntegerField(null = True, blank = True)
    responseTimestamp = models.DateTimeField(null = True, blank = True)
    estimatedResponseTime = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(0), MaxValueValidator(1)])

    defibTime = models.BigIntegerField(null = True, blank = True, validators=[MinValueValidator(-2)])
    defibTimestamp = models.DateTimeField(null = True, blank = True)
    estimatedDefibTimestamp = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(0), MaxValueValidator(1)])
    firstDefibWho = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(5)]) 

    ttm = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(5)])
    ttmTemp =models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(400)])
    drugs = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(7)])
    airwayControl = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(15)])
    cprQuality = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(1)])
    shocks = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2)])
    
    drugTimings = models.BigIntegerField(null = True, blank = True) # time interval from incoming call to the time vascular acces is obtained and the first drug is given
    drugTimingsTimestamp = models.DateTimeField(null = True, blank = True)
    estimatedDrugTimings = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(0), MaxValueValidator(1)])

    vascularAccess = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(4)])
    mechanicalCPR = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(3)])
    targetVent = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(3)])
    reperfusionAttempt = models.SmallIntegerField(null = True, blank = True, validators=[MinValueValidator(-2), MaxValueValidator(8)])

ohca/templates/ohca/dsz.html
{% extends 'ohca/form_base.html' %}

{% block content %}

    <!-- -------submit message-------- -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>{{message}}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <!-- -------submit message-------- -->

    <h2 style="text-align:center;">Prenos podatkov DSZ</h2>
    <div class="text-center" style="padding-top: 20px;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card text-center container d-table" style="width: 100%; height:50vh;">
                <div class="card-body file-upload-wrapper d-table-cell align-middle">
                    <input type="file" id="input-file" class="file-upload" name="document" data-height="500" hidden />
                    <label for="input-file">
                        <ion-icon style="font-size: 15vw; color:#007bff;" name="cloud-upload-outline"></ion-icon>
                        <header id="file-chosen">Kliknite ikono za izbor datoteke</header>
                    </label>
                </div>
            </div>
            
            <button type="submit" class="btn btn-primary" style="min-height:5vh; margin-top: 20px; width: 100%;">Naloži</button>
        </form>
    </div>

    <script>
        const inputFileField = document.getElementById('input-file');
        const fileChosen = document.getElementById('file-chosen');
        inputFileField.addEventListener('change', function(){
            fileChosen.textContent = this.files[0].name
        })
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

{% endblock %}

ohca/templates/ohca/error_page.html
{% extends 'ohca/form_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="POST" action="" id="form2">
        {% csrf_token %}
        {% load cache %}
        {% cache 86600 errorform %}
        <p> </p>
        <p> </p>
        Vpišite 12-mestno številko intervencije
        <p> </p>
        <p> </p>
        <div class="form-row">
            <div class="form-group col-md-1 mb-0">
                {{ form2.i1|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i2|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i3|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i4|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i5|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i6|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i7|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i8|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i9|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i10|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i11|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i12|as_crispy_field }}
            </div>
        </div>

        <script id="int_handle" next-id="id_systemID" src="/static/js/intervention_id.js"></script>
        
        <div class="container">
            <div class="row">
                <div class="col-sm text-center">
                    <p>Dispečerski center</p>
                    <p id="dsz">-----</p>
                </div>
                <div class="col-sm text-center">
                    <p>Datum intervencije</p>
                    <p id="dateInt">--/--/----</p>
                </div>
                <div class="col-sm text-center">
                    <p>Dnevna št. intervencije</p>
                    <p id="intNum">-----</p>
                </div>
            </div>
        </div>

        <!-- <p>{{ formset|crispy }}</p> -->
        

        

        {% with '"adWithdraw", "adHospitalName", "adBystAge", "ecgopt", "allDrugs", "airway", "adTtmTemp", "adTargetBP", "adPh", "adLactate", "adShocks"' as list %}

        {% for field in form1 %}

        {% if field.name not in list %}

        {% if field.name == "cardiacArrest" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>Če ste na obe vprašanji odgovorili z DA nadaljujte z izpolnjevanjem.</p>

        {% elif field.name == "name" %}
            <h2 style='font-weight: 600; font-size: 25px'> 1. Podatki o pacientu</h2>
            <p>{{ field|as_crispy_field }}</p>
            


        {% elif field.name == "dateOfCA" %}
            <h2 style='font-weight: 600; font-size: 25px'> 2. Osnovni podatki</h2>
            <p>{{ field|as_crispy_field }}</p>
  
        {% elif field.name == "reaTimestamp" %}
            <h2 style='font-weight: 600; font-size: 25px'> 3. Časovnica</h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "reaLocation" %}
            <h2 style='font-weight: 600; font-size: 25px'> 4. Podatki o srčnem zastoju</h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "noFirstResponder" %}
            <h2 style='font-weight: 600; font-size: 25px'> 5. Odziv dispečerja in očividca</h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "helperWho" %}
            <h2 style='font-weight: 600; font-size: 25px'> 6. Prvi posredovalci </h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "AEDconn" %}
            <h2 style='font-weight: 600; font-size: 25px'> 7. Ritem</h2>
            <p>{{ field|as_crispy_field }}</p>

            {% elif field.name == "stemiPresent" %}
            <p>{{ form1.ecg|as_crispy_field }}</p>
            <p>{{ field|as_crispy_field }}</p>

        
        {% elif field.name == "ecgOptions" %}
       
        <p>{{ form1.ecgopt|as_crispy_field }}</p>
        
        {% elif field.name == "airwayControl" %}
            <p>{{ form1.airway|as_crispy_field }}</p>

        {% elif field.name == "ttmTemp" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adTtmTemp|as_crispy_field }}</p>

            {% elif field.name == "lactate" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adLactate|as_crispy_field }}</p>

            {% elif field.name == "targetBP" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adTargetBP|as_crispy_field }}</p>

            {% elif field.name == "shocks" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adShocks|as_crispy_field }}</p>

            {% elif field.name == "hospitalName" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adHospitalName|as_crispy_field }}</p>

            {% elif field.name == "ageBystander" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adBystAge|as_crispy_field }}</p>

            {% elif field.name == "rosc" %}
            <h2 style='font-weight: 600; font-size: 25px'> 8. Izhod po oživljanju </h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "drugs" %}
            <h2 style='font-weight: 600; font-size: 25px'> 9. Zdravljenje </h2>
            <p>{{ form1.allDrugs|as_crispy_field }}</p>

        {% elif field.name == "ph" %}
            <h2 style='font-weight: 600; font-size: 25px'> 10. Laboratorijski izvidi </h2>
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adPh|as_crispy_field }}</p>

        {% elif field.name == "discDate" %}
            <h2 style='font-weight: 600; font-size: 25px'> 11. Dolgotrajen izid </h2>
            <p>{{ field|as_crispy_field }}</p>
        
        {% elif field.name == "treatmentWithdrawnTimestamp" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adWithdraw|as_crispy_field }}</p>

        {% elif field.name == "ssep" %}
            <h2 style='font-weight: 300; font-size: 20px'> Nevroprognostični testi </h2>
            <p>{{ field|as_crispy_field }}</p>

            {% elif field.name == "airwayControl" %}
            <p>{{ form1.airway|as_crispy_field }}</p>



        {% else %}
            <p>{{ field|as_crispy_field }}</p>

        {% endif %}
        {% endif %}
        {% endfor %}
        {% endwith %}

        <!-- <form action="#"> -->
        <script src="/static/js/formPersistence.js"></script>
        <script src="/static/js/errorValidation.js"></script>
        
        <input type="submit" class="btn btn-dark" value="Submit" onclick="saveFormToCookie(); handleDoubleField()" onload="saveFormToCookie()">
        {% endcache %}
    </form>

{% endblock %}

ohca/templates/ohca/form_page.html
{% extends 'ohca/form_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="POST" action="" id="form2">
        {% csrf_token %}
        {% load cache %}
        {% cache 86600 form1 %}
        <p> </p>
        <p> </p>
        Vpišite 12-mestno številko intervencije
        <p> </p>
        <p> </p>
        <div class="form-row">
            <div class="form-group col-md-1 mb-0">
                {{ form2.i1|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i2|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i3|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i4|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i5|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i6|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i7|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i8|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i9|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i10|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i11|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
                {{ form2.i12|as_crispy_field }}
            </div>
        </div>

        <script id="int_handle" next-id="id_systemID" src="/static/js/intervention_id.js"></script>
        
        <div class="container">
            <div class="row">
                <div class="col-sm text-center">
                    <p>Dispečerski center</p>
                    <p id="dsz">-----</p>
                </div>
                <div class="col-sm text-center">
                    <p>Datum intervencije</p>
                    <p id="dateInt">--/--/----</p>
                </div>
                <div class="col-sm text-center">
                    <p>Dnevna št. intervencije</p>
                    <p id="intNum">-----</p>
                </div>
            </div>
        </div>

        <!-- <p>{{ formset|crispy }}</p> -->
        

        

        {% with '"adHospitalName", "adBystAge", "ecgopt", "allDrugs", "airway", "adTtmTemp", "adTargetBP", "adPh", "adLactate", "adShocks"' as list %}

        {% for field in form1 %}

        {% if field.name not in list %}

        {% if field.name == "cardiacArrest" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>Če ste na obe vprašanji odgovorili z DA nadaljujte z izpolnjevanjem.</p>

        {% elif field.name == "name" %}
            <h2 style='font-weight: 600; font-size: 25px'> 1. Podatki o pacientu</h2>
            <p>{{ field|as_crispy_field }}</p>
            


        {% elif field.name == "dateOfCA" %}
            <h2 style='font-weight: 600; font-size: 25px'> 2. Osnovni podatki</h2>
            <p>{{ field|as_crispy_field }}</p>
  
        {% elif field.name == "reaTimestamp" %}
            <h2 style='font-weight: 600; font-size: 25px'> 3. Časovnica</h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "reaLocation" %}
            <h2 style='font-weight: 600; font-size: 25px'> 4. Podatki o srčnem zastoju</h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "noFirstResponder" %}
            <h2 style='font-weight: 600; font-size: 25px'> 5. Odziv dispečerja in očividca</h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "helperWho" %}
            <h2 style='font-weight: 600; font-size: 25px'> 6. Prvi posredovalci </h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "AEDconn" %}
            <h2 style='font-weight: 600; font-size: 25px'> 7. Ritem</h2>
            <p>{{ field|as_crispy_field }}</p>

            {% elif field.name == "stemiPresent" %}
            <p>{{ form1.ecg|as_crispy_field }}</p>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "rosc" %}
            <h2 style='font-weight: 600; font-size: 25px'> 8. Izhod po oživljanju </h2>
            <p>{{ field|as_crispy_field }}</p>

        {% elif field.name == "drugs" %}
            <h2 style='font-weight: 600; font-size: 25px'> 9. Zdravljenje </h2>
            <p>{{ form1.allDrugs|as_crispy_field }}</p>

        {% elif field.name == "ph" %}
            <h2 style='font-weight: 600; font-size: 25px'> 10. Laboratorijski izvidi </h2>
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adPh|as_crispy_field }}</p>

        {% elif field.name == "discDate" %}
            <h2 style='font-weight: 600; font-size: 25px'> 11. Dolgotrajen izid </h2>
            <p>{{ field|as_crispy_field }}</p>
        
        {% elif field.name == "ecgOptions" %}
       
        <p>{{ form1.ecgopt|as_crispy_field }}</p>
        
        {% elif field.name == "airwayControl" %}
            <p>{{ form1.airway|as_crispy_field }}</p>

        {% elif field.name == "ttmTemp" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adTtmTemp|as_crispy_field }}</p>

            {% elif field.name == "lactate" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adLactate|as_crispy_field }}</p>

            {% elif field.name == "targetBP" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adTargetBP|as_crispy_field }}</p>

            {% elif field.name == "shocks" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adShocks|as_crispy_field }}</p>

            {% elif field.name == "hospitalName" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adHospitalName|as_crispy_field }}</p>

            {% elif field.name == "ageBystander" %}
            <p>{{ field|as_crispy_field }}</p>
            <p>{{ form1.adBystAge|as_crispy_field }}</p>


        {% else %}
            <p>{{ field|as_crispy_field }}</p>

        {% endif %}
        {% endif %}
        {% endfor %}
        {% endwith %}

        <!-- <form action="#"> -->
        <script src="/static/js/formPersistence.js"></script>
        <script src="/static/js/formValidation.js"></script>
        <input type="submit" class="btn btn-dark" value="Submit" onclick="saveFormToCookie(); handleDoubleField()" onload="saveFormToCookie()">
        {% endcache %}
    </form>

{% endblock %}